import uuid
from datetime import datetime, timezone

from app import db


def new_uuid():
    return str(uuid.uuid4())


def utcnow():
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# SPARTA reference data (read-mostly; refreshed by app/data_loader.py from
# app/data/*.json, which is itself derived from the official SPARTA feed via
# the MISP galaxy CC0 dataset - see README.md "Data provenance").
# ---------------------------------------------------------------------------

class Tactic(db.Model):
    __tablename__ = "tactics"
    id = db.Column(db.String(16), primary_key=True)  # e.g. ST0001
    shortname = db.Column(db.String(64), nullable=False)
    name = db.Column(db.String(128), nullable=False)
    description = db.Column(db.Text, nullable=False)
    display_order = db.Column(db.Integer, nullable=False)
    source_url = db.Column(db.String(256), nullable=False)

    techniques = db.relationship("Technique", back_populates="tactic", lazy="dynamic")


class Technique(db.Model):
    __tablename__ = "techniques"
    id = db.Column(db.String(32), primary_key=True)  # e.g. DE-0001 or DE-0002.01
    name = db.Column(db.String(256), nullable=False)
    description = db.Column(db.Text, nullable=False)
    tactic_id = db.Column(db.String(16), db.ForeignKey("tactics.id"), nullable=False)
    is_subtechnique = db.Column(db.Boolean, default=False, nullable=False)
    parent_id = db.Column(db.String(32), nullable=True)
    segments_csv = db.Column(db.String(256), nullable=False, default="")  # comma-joined segment tags
    source_url = db.Column(db.String(256), nullable=False)

    tactic = db.relationship("Tactic", back_populates="techniques")

    @property
    def segments(self):
        return [s for s in self.segments_csv.split(",") if s]


class Mitigation(db.Model):
    __tablename__ = "mitigations"
    id = db.Column(db.String(16), primary_key=True)  # e.g. CM0001
    name = db.Column(db.String(256), nullable=False)
    description = db.Column(db.Text, nullable=False)
    nist_refs_csv = db.Column(db.String(1024), nullable=False, default="")
    iso_refs_csv = db.Column(db.String(1024), nullable=False, default="")
    source_url = db.Column(db.String(256), nullable=False)


# ---------------------------------------------------------------------------
# User-authored data: the system under review and the generated findings.
# ---------------------------------------------------------------------------

SEGMENT_CHOICES = [
    ("space", "Space segment (bus / payload / onboard software)"),
    ("ground", "Ground segment (mission ops, TT&C ground stations)"),
    ("link", "Link segment (RF uplink/downlink, crosslink, RF ground equipment)"),
    ("user", "User segment (end-user terminals, client applications)"),
    ("launch", "Launch segment (launch vehicle, integration facility)"),
    ("supply_chain", "Supply chain (component suppliers, integrators, contractors)"),
]


class SpaceSystem(db.Model):
    """A system-under-review that a user describes for threat modeling."""
    __tablename__ = "space_systems"
    id = db.Column(db.String(36), primary_key=True, default=new_uuid)
    name = db.Column(db.String(200), nullable=False)
    mission_type = db.Column(db.String(120), nullable=True)
    description = db.Column(db.Text, nullable=True)
    segments_csv = db.Column(db.String(256), nullable=False, default="")
    uses_third_party_auth = db.Column(db.Boolean, default=False)
    uses_commercial_ground_station = db.Column(db.Boolean, default=False)
    has_encrypted_tt_and_c = db.Column(db.Boolean, default=False)
    has_supply_chain_program = db.Column(db.Boolean, default=False)
    is_constellation = db.Column(db.Boolean, default=False)
    is_nis2_in_scope = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=utcnow)
    updated_at = db.Column(db.DateTime, default=utcnow, onupdate=utcnow)

    findings = db.relationship(
        "Finding", back_populates="system", cascade="all, delete-orphan", lazy="dynamic"
    )

    @property
    def segments(self):
        return [s for s in self.segments_csv.split(",") if s]

    @segments.setter
    def segments(self, values):
        clean = [v for v in values if v in dict(SEGMENT_CHOICES)]
        self.segments_csv = ",".join(clean)


SEVERITY_ORDER = {"low": 0, "medium": 1, "high": 2, "critical": 3}


class Finding(db.Model):
    """One technique flagged as applicable to a SpaceSystem, with a severity
    and an analyst-editable note. Generated by app/engine.py, then reviewed
    and adjusted by a human analyst - this table is the human-in-the-loop
    record, not a black-box verdict."""
    __tablename__ = "findings"
    id = db.Column(db.String(36), primary_key=True, default=new_uuid)
    system_id = db.Column(db.String(36), db.ForeignKey("space_systems.id"), nullable=False)
    technique_id = db.Column(db.String(32), db.ForeignKey("techniques.id"), nullable=False)
    severity = db.Column(db.String(16), nullable=False, default="medium")
    rationale = db.Column(db.Text, nullable=True)
    analyst_note = db.Column(db.Text, nullable=True)
    status = db.Column(db.String(16), nullable=False, default="open")  # open / mitigated / accepted / false_positive
    created_at = db.Column(db.DateTime, default=utcnow)

    system = db.relationship("SpaceSystem", back_populates="findings")
    technique = db.relationship("Technique")
